### ISSUE TITLE
Unsure how to open user manager

### ISSUE THREAD

**Issue by kamn8r** [4rm/Appstream-User-Manager#1]
After downloading the zip, extracting, and trying to run AppstreamUserManager nothing happens. I have python3 installed. Do you have any insight as to why this might not be launching?

**Comment by 4rm** [comment]
Couple things: 

1) You shouldn't need to download the .zip if you aren't making any modifications. The .exe can be downloaded here: https://github.com/4rm/Appstream-User-Manager/releases/download/v2.1/Appstream.User.Manager.exe
2) Are you on a non-Windows computer? I haven't tested on Mac or Linux
3) It does take a while to launch sometimes. Maybe let it sit for a bit?
4) Windows might be blocking it. Make sure to allow it through Smartscreen when the prompt comes up

**Comment by kamn8r** [comment]
![Appstream User Manager Error](https://user-images.githubusercontent.com/43175422/97630976-4e3de980-19fe-11eb-92fe-22adbb350372.png)

Hi 4rm! Thank you. Using the .exe worked. I am using a Windows computer. After entering my access and secret key I receive the error shown in the attached image that says _Failed to execute script AppstreamUserManager_. Are there any logs you would like me to pull, or troubleshooting method you would like me to try? I appreciate any help you can provide. Thanks again.

**Comment by 4rm** [comment]
Glad we're making some progress!

First, please try running as an administrator.

Then, if that doesn't work, try the following:
1. Open the folder that the .exe is located in
2. Shift-right-click (hold shift while you're right-clicking) in the empty space, and select "Open PowerShell window here"
3. Type in `.\Appstream.User.Manager.exe` or `.\whatever-your-exe-name-is-here`
4. Try logging in again. If it crashes, you should see some crash info in the PowerShell window

Hope this helps!

**Comment by kamn8r** [comment]
![Error](https://user-images.githubusercontent.com/43175422/97879200-57240900-1ce5-11eb-828d-c8c4ac7c075b.png)
I tried running as administrator and received the same error as before. I also tried your second recommendation of running PowerShell in the same location as the .exe file. The same error still appeared. I appreciate these troubleshooting tips! Do you have any other ideas I might be able to test to get this working? Thanks again for your help.

**Comment by 4rm** [comment]
Hmm, okay, this is a bit odd — I'd like to try running the program from the code if that's okay with you.

1. Download the code .zip from [here](https://github.com/4rm/Appstream-User-Manager/archive/v2.1.zip)
2. Extract the .zip
3. Open your command prompt and run `pip install boto3 keyring requests`
4. Open PowerShell in the same folder as the code, and try running the program with `python AppstreamUserManager.py` (Note that this is the **`.py`** and not the `.exe`
5. Let me know what the console says if it fails again

Hope this helps!

**Comment by kamn8r** [comment]
Hi again 4rm! I can't thank you enough for continuing to help me troubleshoot this. I installed the package referenced in step 3, then executed the python script and this is the error that was presented to me. 

![2](https://user-images.githubusercontent.com/43175422/98265630-ed0e9c80-1f4e-11eb-9f2f-f095f951ee12.png)

**Comment by 4rm** [comment]
Hi again!

I've attempted a fix here: https://raw.githubusercontent.com/4rm/Appstream-User-Manager/master/AppstreamUserManager.py

You can either download the above code, and replace the .py that you have downloaded, or copy-paste from the link and replace all the code in the .py you already have downloaded. Then try running the same way as last time.

Hope this works! If it does, I'll try repackaging as an .exe and push a new release.

**Comment by kamn8r** [comment]
![success](https://user-images.githubusercontent.com/43175422/98558605-420e2380-226b-11eb-9d0a-deb34d5b1fcf.png)
Success! I did a light test of functionality and everything appears to be working great. I appreciate you taking the time to work with me. I'm looking forward to using this to manage our User Pool and Stack assignments. Thanks again!

**Comment by 4rm** [comment]
Glad I could help! Just published a new release, so you won't have to launch from PowerShell. Hope everything goes well!
